library/books/urls.py
from django.contrib import admin
from django.urls import path,include

from books import views
app_name="books"
urlpatterns = [

    path('',views.home,name='home'),
    path('add_books',views.add_books,name='add_books'),
    path('view_books',views.view_books,name='view_books'),
    path('detail/<int:p>',views.detail,name='detail'),
    path('edit/<int:p>',views.edit,name='edit'),
    path('delete/<int:p>',views.delete,name='delete'),
    path('search',views.search,name='search'),

]

library/library/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('books.urls')),
    path('user/',include('user.urls')),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

library/user/urls.py
from django.contrib import admin
from django.urls import path
from user import views
app_name="user"
urlpatterns = [

    path('register',views.register,name='register'),
    path('login',views.user_login,name='login'),
    path('login',views.user_logout,name='logout'),


]

library/books/models.py
from django.db import models

# Create your models here.
class Book(models.Model):
    title=models.CharField(max_length=20)
    author=models.CharField(max_length=20)
    language=models.CharField(max_length=20)
    price=models.IntegerField()
    pages=models.IntegerField()
    cover=models.ImageField(upload_to="images")
    pdf=models.FileField(upload_to="pdf" )

library/books/views.py
from django.shortcuts import render,redirect
from books.models import Book
from django.contrib.auth.decorators import login_required
# Create your views here.
def home(request):
    return render(request,'home.html')
@login_required
def add_books(request):
    if(request.method=="POST"):
        t=request.POST['t']
        a=request.POST['a']
        p=request.POST['p']
        pa=request.POST['pa']
        l=request.POST['l']
        c=request.FILES['c']
        f=request.FILES['f']
        b=Book.objects.create(title=t,author=a,price=p,pages=pa,language=l,cover=c,pdf=f)  #create a new record
        b.save() #save the record inside table book
        return view_books(request)
    return render(request,'add_books.html')
@login_required
def view_books(request):
    k=Book.objects.all()  #read all records from table
    context={'book':k}    # pass all data from views to html file.context is dictiony type

    return render(request,'view_books.html',context)

def detail(request,p):
    b=Book.objects.get(id=p)
    context={'book':b}
    return render(request, 'detail.html',context)
def edit(request,p):
    b=Book.objects.get(id=p)
    if (request.method == "POST"):  # After submitting form
        b.title  = request.POST['t']
        b.author = request.POST['a']
        b.price = request.POST['p']
        b.pages = request.POST['pa']
        b.language = request.POST['l']
        if(request.FILES.get('c')==None):
            b.save()
        else:
            b.cover=request.FILES.get('c')
        if (request.FILES.get('f') == None):
            b.save()
        else:
            b.pdf = request.FILES.get('f')

        b.save()
        return redirect('books:view_books')

    context={'book':b}
    return render(request,'edit.html',context)

def delete(request,p):
    b = Book.objects.get(id=p)
    b.delete()
    return redirect('books:view_books')

from django.db.models import Q
def search(request):
    b=None   # initialised to none ...if there is no query then automatically none
    query=""
    if (request.method == "POST"):  # after form submission
        query=request.POST['q']
        if query:
            b = Book.objects.filter(Q(title__icontains=query) | Q(author__icontains=query))


    return render(request, 'search.html',{'books':b,'query':query})

library/user/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.models import User
from django.http import HttpResponse
# Create your views here.
def register(request):
    if (request.method == "POST"):
        u = request.POST['u']
        p = request.POST['p']
        cp = request.POST['cp']
        e = request.POST['e']
        f = request.POST['f']
        l = request.POST['l']
        if(p==cp):
            u=User.objects.create_user(username=u,password=p,email=e,first_name=f,last_name=l)
            u.save()
        else:
            return HttpResponse("password should be same")

        return redirect('books:home')

    return render(request,'register.html')


from django.contrib.auth import login,authenticate,logout
from django.http import HttpResponse


def user_login(request):
    if(request.method=='POST'):
        u=request.POST['u']
        p=request.POST['p']

        user=authenticate(username=u,password=p)  #cheecks whether the dtails entered by user is correct or nor
        if user:     # if user already exist
            login(request,user)
            return redirect('books:home')
        else:
            return HttpResponse("invalid credentials")

    return render(request,'login.html')

def user_logout(request):
    logout(request)
    return redirect('users:login')

library/templates/add_books.html
{% extends 'base.html' %}
{% load static %}
{% block content%}
<div class="container mt-3 text-light"></div>
<h1 class="text-center text-light">add books</h1>
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="mb-3">
  <label  class="form-label">title</label>
  <input type="text" class="form-control" name="t" placeholder="enter title">
</div>
    <div class="mb-3">
  <label  class="form-label">author</label>
  <input type="text" class="form-control" name="a" placeholder="enter author">
</div>

    <div class="mb-3">
  <label  class="form-label">price</label>
  <input type="number" class="form-control" name="p" placeholder="enter price">
</div>

    <div class="mb-3">
  <label  class="form-label">pages</label>
  <input type="number" class="form-control" name="pa" placeholder="enter pages">
</div>

    <div class="mb-3">
  <label  class="form-label">language</label>
  <input type="text" class="form-control" name="l" placeholder="enter langugage">
</div>
    <div class="mb-3">
  <label  class="form-label">cover</label>
  <input type="file" class="form-control" name="c" >
</div>
    <div class="mb-3">
  <label  class="form-label">pdf</label>
  <input type="file" class="form-control" name="f" >
</div>
    <div class="mb-3">
    <input type="submit" class="btn btn-dark text-light px-4" >
  </div>
</form>

{% endblock%}

library/templates/base.html
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>home</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

</head>
<body style="background-image: url('{% static "images/lib.png" %}');" >
<h1 style="color: yellow;">Welcome to Home</h1>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container">
    <a class="navbar-brand" href="#">Library app</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'books:home' %}">Home</a>
        </li>

{% if user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'books:add_books' %}">add books</a>
        </li>
          <li class="nav-item">
          <a class="nav-link" href="{% url 'books:view_books' %}">view books</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'user:logout' %}">logout</a>
        </li>
{% else %}
          <li class="nav-item">
          <a class="nav-link" href="{% url 'user:login' %}">login</a>
        </li>
          <li class="nav-item">
          <a class="nav-link" href=" {% url 'user:register' %}">register</a>
      </li>
        {% endif %}
      </ul>
        {% if user.is_authenticated %}
        <form class="d-flex" action="{% url 'books:search' %}" method="POST">
            {% csrf_token %}
              <input class="form-control me-2" type="search" name="q" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
        </form>
        {% endif %}
    </div>
  </div>
</nav>
{% block content %}
{% endblock %}

library/templates/delete.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container mt-3">
    <h1 class="text-center text-light"> Delete Book Details</h1></div>
{% endblock %}

library/templates/detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container mt-3">
    <h1 class="text-center text-light">Book Details</h1></div>
<div class="card mb-3 mx-auto" style="max-width: 40%;">
  <div class="row g-0">
    <div class="col-md-4 p-4">
      <img src="{{book.cover.url}}" class="rounded-start" height="270px" width="150px" alt="...">
    </div>
    <div class="col-md-8">
      <div class="card-body p-5 ms-4">
        <h5 class="card-title mt-3 mb-4">Book title:{{book.title}}</h5>
        <p class="card-text mb-4" >Language:{{book.language}}</p>
        <p class="card-text mb-4" >Author:{{book.author}}</p>
        <h5 class="card-text mb-4" >Price:{{book.price}}</h5>

      </div>
    </div>
  </div>
</div>
{% endblock %}

library/templates/edit.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container mt-3">
    <h1 class="text-center text-light"> Edit Book Details</h1></div>
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="mb-3">
  <label  class="form-label">title</label>
  <input type="text" class="form-control" name="t" value="{{book.title}}" placeholder="enter title">
</div>
    <div class="mb-3">
  <label  class="form-label">author</label>
  <input type="text" class="form-control" name="a" value="{{book.author}}" placeholder="enter author" >
</div>

    <div class="mb-3">
  <label  class="form-label">price</label>
  <input type="number" class="form-control" name="p" value="{{book.price}}" placeholder="enter price" >
</div>

    <div class="mb-3">
  <label  class="form-label">pages</label>
  <input type="number" class="form-control" name="pa" value="{{book.pages}}" placeholder="enter pages" >
</div>

    <div class="mb-3">
  <label  class="form-label">language</label>
  <input type="text" class="form-control" name="l" value="{{book.language}}" placeholder="enter language">
</div>
    <div class="mb-3">
        <img src="{{book.cover.url}}" height="100px" width="100px">
  <label  class="form-label">cover</label>
  <input type="file" class="form-control" name="c" >
</div>
    <div class="mb-3">
        <a href="{{book.pdf.url}}">
  <label  class="form-label">pdf</label>
  <input type="file" class="form-control" name="f" >
</div>
    <div class="mb-3">
    <input type="submit" class="btn btn-dark text-light px-4" >
  </div>
</form>
{% endblock %}

library/templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<h1 class="text-center text-light">welcome to home page</h1>
{% if user.is_authenticated %}
<h5>{{user.username}}</h5>
{% else %}
<h5>guest</h5>
{% endif %}

{% endblock %}

library/templates/login.html
{% extends 'base.html' %}
{% load static %}
{% block content %}


<div class="container mt-3 text-light">

<h1 class="text-center">welcome to login page</h1>
<form method="POST" >
    {% csrf_token %}
     <div class="mb-3">
  <label  class="form-label">Username</label>
  <input type="text" class="form-control" name="u" placeholder="enter username">
</div>
<div class="mb-3">
  <label  class="form-label">Password</label>
  <input type="password" class="form-control" name="p" placeholder="enter password">
</div>
    <div class="mb-3">
    <input type="submit" class="btn btn-dark text-light px-4" >
  </div>
</form>
</div>
{% endblock %}

library/templates/register.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container mt-3 text-light">
<h1 class="text-center">welcome to register page</h1>
<form method="POST" >
    {% csrf_token %}
     <div class="mb-3">
  <label  class="form-label">Username</label>
  <input type="text" class="form-control" name="u" placeholder="enter username">
</div>
<div class="mb-3">
  <label  class="form-label">Password</label>
  <input type="password" class="form-control" name="p" placeholder="enter password">
</div>
<div class="mb-3">
  <label  class="form-label">Confirm Password</label>
  <input type="password" class="form-control" name="cp" placeholder="enter confirm password">
</div>
    <div class="mb-3">
  <label  class="form-label">Email</label>
  <input type="text" class="form-control" name="e" placeholder="enter email">
</div>
     <div class="mb-3">
  <label  class="form-label">Firstname</label>
  <input type="text" class="form-control" name="f" placeholder="enter first name">
</div>
    <div class="mb-3">
  <label  class="form-label">Lastname</label>
  <input type="text" class="form-control" name="l" placeholder="enter last name">
</div>
    <div class="mb-3">
    <input type="submit" class="btn btn-dark text-light px-4" >
  </div>


</form>
</div>
{% endblock %}

library/templates/search.html
{% extends 'base.html' %}
{% load static %}
{% block content %}


<div class="container mt-3 text-light">
<h1 class="text-center">You have searched for <span class="text-light">{{query}}</span></h1>
<div class="mx-auto w-75">

     {% if books == None %} <!--query empty-->
    <h4 class="text-center text-danger">No Results Found</h4>


    {% elif books.exists %} <!-- if query results -->
    <table class="table table-bordered w-75 mx-auto mt-4 text-light">
<tr class="fw-bold fs-4">
<th>Title</th>
<th>Author</th>
<th>Price</th>
    <th>Language</th>
    <th>pages</th>
    <th>cover</th>
    <th>document</th>


</tr>

{%  for  i   in   books %}
    <tr class="text-center">
<td>{{i.title}}</td><td>{{i.author}}</td><td>{{i.price}}</td><td>{{i.language}}</td><td>{{i.pages}}</td>
        <td class="p-3"><img src="{{i.cover.url}}" height="150px" width="100px" class="img-thumbnail "   ></td>
        <td><a href="{{i.pdf.url}}">Download</a></td>

    </tr>
        {% endfor %}

    </table>


    {% else %}
    <h4 class="text-center text-danger">No Results Found</h4>


    {% endif %}

</div>
</div>
{% endblock %}

library/templates/view_books.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container mt-3 text-light"></div>
 <h2 class="text-center text-light">Book List</h2>
<table class="table table-bordered w-75 mx-auto mt-4 text-light">
<tr class="fw-bold fs-4">
<th>Title</th>
<th>Author</th>
<th>Price</th>
    <th>Language</th>
    <th>pages</th>
    <th>cover</th>
    <th>document</th>
    <th>View</th>
    <th>Edit</th>
    <th>Delete</th>

</tr>

{%  for  i   in   book %}
    <tr class="text-center">
<td>{{i.title}}</td><td>{{i.author}}</td><td>{{i.price}}</td><td>{{i.language}}</td><td>{{i.pages}}</td>
        <td class="p-3"><img src="{{i.cover.url}}" height="150px" width="100px" class="img-thumbnail "   ></td>
        <td><a href="{{i.pdf.url}}">Download</a></td>
        <td><a href="{% url 'books:detail' i.id %}" class="btn btn-secondary text-light">View</a></td>
        <td><a href="{% url 'books:edit' i.id %}" class="btn btn-secondary text-light">Edit</a></td>
        <td><a href="{% url 'books:delete' i.id %}" class="btn btn-secondary text-light">Delete</a></td>

    </tr>
    {% endfor %}
    </table>
<!--<ol>
    {% for i in book %}
    <li>book details</li>
    <ul>
        <li>title {{i.title}}</li>
        <li>author {{i.author}}</li>
        <li>price {{i.price}}</li>
        <li>pages {{i.pages}}</li>
        <li>language {{i.language}}</li>
        <li>cover:  {{i.cover}}</li>
        <li>pdf: {{i.pdf}}</li>

    </ul>
{% endfor %}
</ol>-->
{% endblock %}