ecommerce/cart/urls.py
from django.contrib import admin
from django.urls import path
from cart import views
app_name='cart'

from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [

    path('<int:i>',views.addtocart,name='addtocart'),
    path('cartview',views.cart_view,name='cartview'),
    path('cart_remove/<int:i>',views.cart_remove,name='cart_remove'),
    path('cart_fullremove/<int:i>',views.cart_fullremove,name='cart_fullremove'),
    path('orderform',views.orderform,name='orderform'),
    path('payment-status/<str:p>',views.payment_status,name="status"),
    path('orderview',views.orderview,name="orderview"),



]

ecommerce/ecommerce/urls.py
from django.contrib import admin
from django.urls import path,include
from shop import views


from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('shop.urls')),
    path('cart/',include('cart.urls')),
    path('search/', include('search.urls')),


]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

ecommerce/search/urls.py
from django.contrib import admin
from django.urls import path
from search import views
app_name='search'

from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [

    path('',views.searchproducts,name='search'),




]

ecommerce/shop/urls.py
from django.contrib import admin
from django.urls import path
from shop import views
app_name='shop'

from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [

    path('',views.categories,name='categories'),
    path('products/<int:i>',views.products,name='products'),
    path('detail/<int:i>',views.productdetail,name='detail'),
    path('register', views.register, name='register'),
    path('login', views.user_login, name='login'),
    path('logout', views.user_logout, name='logout'),
    path('addcategories', views.addcategories, name='addcategories'),
    path('addproducts', views.addproducts, name='addproducts'),
    path('addstock/<int:i>', views.addstock, name='addstock'),
    path('addtocart', views.addtocart, name='addtocart'),


]

ecommerce/cart/models.py
from django.db import models
from shop.models import Product
from django.contrib.auth.models import User

class Cart(models.Model):
    product = models.ForeignKey(Product,on_delete=models.CASCADE)
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    quantity = models.IntegerField()
    date_added = models.DateTimeField(auto_now_add=True)

    def subtotal(self):
        return self.product.price * self.quantity

    def __str__(self):
        return self.product.name

class Order_detail(models.Model):
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    user=models.ForeignKey(User, on_delete=models.CASCADE)
    no_of_items=models.IntegerField()
    address=models.TextField()
    phone=models.BigIntegerField()
    pin=models.IntegerField()

    order_id=models.CharField(max_length=30)
    payment_status=models.CharField(max_length=30, default="pending")
    delivery_status=models.CharField(max_length=30, default="pending")
    ordered_date=models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.order_id

class Payment(models.Model):
    name=models.CharField(max_length=30)
    amount=models.IntegerField()
    order_id=models.CharField(max_length=30)
    razorpay_payment_id=models.CharField(max_length=30,blank=True)
    paid=models.BooleanField(default=False)

    def __str__(self):
        return self.order_id

ecommerce/search/models.py
from django.db import models

# Create your models here.

ecommerce/cart/views.py
from django.shortcuts import render,redirect
from shop.models import Product
from cart.models import Cart
from cart.models import Payment,Order_detail

import razorpay
# Create your views here.
def addtocart(request,i):
    p=Product.objects.get(id=i)
    u=request.user    #login user


    try:
        c = Cart.objects.get(user=u, product=p)   #if that product is already present inside tble for the current user
        c.quantity+=1
        c.save()
        p.stock -= 1
        p.save()

    except:  #if not present
        c = Cart.objects.create(product=p, user=u, quantity=1)  #it will add new record with quantity=1
        c.save()
        p.stock -= 1
        p.save()



    return redirect('cart:cartview')
def   cart_view(request):
    u=request.user
    c=Cart.objects.filter(user=u)

    # calculate total value
    total=0
    for i in c:
        total+=i.quantity*i.product.price

    context={'cart':c,'total':total}
    return render(request,'cart.html',context)

def cart_remove(request, i):
    u=request.user
    p=Product.objects.get(id=i)
    try:
        c = Cart.objects.get(user=u, product=p)
        if (c.quantity > 1):
            c.quantity -= 1
            c.save()
            p.stock += 1
            p.save()
        else:
            c.delete()
            p.stock += 1
            p.save()
    except:
        pass






    return redirect('cart:cartview')
def cart_fullremove(request,i):
    u = request.user
    p = Product.objects.get(id=i)
    try:
        c = Cart.objects.get(user=u, product=p)
        c.delete()
        p.stock += c.quantity
        p.save()

    except:
        pass

    return redirect('cart:cartview')
def orderform(request):
    if request.method=="POST":
        a = request.POST['a']
        pn = request.POST['pn']
        n = request.POST['n']

        u=request.user
        c=Cart.objects.filter(user=u)

        total=0
        for i in c:
            total+=i.product.price*i.quantity
        print (total)



        #razorpay connection
        client=razorpay.Client(auth=('rzp_test_HSpVqk4ONJaQSA','BUgpAVzh6P7XpEirZ3EhNked'))

        #razorpay order creation
        response_payment=client.order.create(dict(amount=total*100,currency='INR'))
        order_id=response_payment['id'] #retreive oder id from response
        status=response_payment['status']  #retrive status from response
        if(status=="created"):
            p=Payment.objects.create(name=u.username,amount=total,order_id=order_id)
            p.save()

            for i in c:
                o = Order_detail.objects.create(product=i.product,user=i.user,phone=pn,address=a,pin=n,order_id=order_id,no_of_items=i.quantity)
                o.save()







            context = {'payment': response_payment, 'name': u.username}

        return render(request, 'payment.html', context) #

    return render(request, 'orderform.html')

from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.models import User
from django.contrib.auth import login

@csrf_exempt

def payment_status(request,p):
    user=User.objects.get(username=p)  #reteive user object
    login(request,user)


    response=request.POST   #razorpay response after successful paymenft
    print(response)

    # check validy of payment details recieved from razorpay

    param_dict={
        'razorpay_order_id':response['razorpay_order_id'],
        'razorpay_payment_id':response['razorpay_payment_id'],
        'razorpay_signature':response['razorpay_signature']
        }
    client = razorpay.Client(auth=('rzp_test_HSpVqk4ONJaQSA','BUgpAVzh6P7XpEirZ3EhNked'))

    try:
        status=client.utility.verify_payment_signature(param_dict)   #for checking payment details
                                                                     #we pass param_dict to verify_payment_signature function
        print(status)

        p=Payment.objects.get(order_id=response['razorpay_order_id'])#After successful payment retrieve the payment record matching with response['order_id]
        p.razorpay_payment_id=response['razorpay_payment_id']#assigns response [payment id] to razorpay_payment_id
        p.paid=True  #ASSIGN paid value to true
        p.save()

        o = Order_detail.objects.filter(order_id=response['razorpay_order_id'])#After successful payment retrieve the order_details records matching with respo
        for i in o:
            i.payment_status = "completed"
            i.save()

        # to remove cart items after sucessful paymnt
        c=Cart.objects.filter(user=user)
        c.delete()







    except:
        pass







    return render(request, 'payment-status.html')

def orderview(request):
    u = request.user
    o = Order_detail.objects.filter(user=u,payment_status = "completed")
    context={'orders':o}
    return render(request, 'orderview.html',context)

ecommerce/search/views.py
from django.shortcuts import render
from shop.models import Product
from django.db.models import Q
# Create your views here.
def searchproducts(request):
    p=None
    query=""
    if (request.method == "POST"):
        query=request.POST['q']
        if query:
            p =Product.objects.filter(Q(name__icontains=query) | Q(desc__icontains=query))


    return render(request, 'search.html',{'pro':p,'query':query})

ecommerce/templates/addcategories.html
{% extends 'base.html' %}
{% load static %}
{% block content %}


<div class="container mt-3 text-dark bg-secondary">

<h1 class="text-center">Add Category Details</h1>
<form method="POST" enctype="multipart/form-data" >
    {% csrf_token %}
     <div class="mb-3">
  <label  class="form-label">Category name</label>
  <input type="text" class="form-control" name="n" placeholder="Category name">
</div>
<div class="mb-3">
  <label  class="form-label">Image</label>
  <input type="file" class="form-control" name="i" >
</div>
<div class="mb-3">
  <label  class="form-label">Description</label>
    <textarea class="form-control" name="d"></textarea>
</div>

    <div class="mb-3">
    <input type="submit" class="btn btn-dark text-light px-4" >
  </div>
</form>
</div>
{% endblock %}

ecommerce/templates/addproducts.html
{% extends 'base.html' %}
{% load static %}
{% block content %}


<div class="container mt-3 text-dark bg-secondary">

<h1 class="text-center">Add Product Details</h1>
<form method="POST" enctype="multipart/form-data" >
    {% csrf_token %}
     <div class="mb-3">
  <label  class="form-label">Product name</label>
  <input type="text" class="form-control" name="n" placeholder="enter  Product name">
</div>
<div class="mb-3">
  <label  class="form-label">Image</label>
  <input type="file" class="form-control" name="i" >
</div>
<div class="mb-3">
  <label  class="form-label">Description</label>
    <textarea class="form-control" name="d"></textarea>
</div>

<div class="mb-3">
  <label  class="form-label">Price</label>
  <input type="number" class="form-control" name="p" placeholder="enter  Price">
</div>
<div class="mb-3">
  <label  class="form-label">Stock</label>
  <input type="number" class="form-control" name="s" placeholder="enter  stock">
</div>



<div class="mb-3">
  <label  class="form-label">Category</label>
    <select name="c" class="form-control">
        {% for i in links %}
        <option value="{{i}}">{{i.name}}</option>
        {% endfor %}
    </select>

</div>







    <div class="mb-3">
    <input type="submit" class="btn btn-dark text-light px-4" >
  </div>
</form>
</div>
{% endblock %}

ecommerce/templates/addstock.html
{% extends 'base.html' %}
{% load static %}
{% block content %}


<div class="container mt-3 text-dark bg-secondary">

<h1 class="text-center">Add Product stock</h1>
<form method="POST" >
    {% csrf_token %}


<div class="mb-3">
  <label  class="form-label">Stock</label>
  <input type="number" class="form-control" name="n" value="{{pro.stock}}"  >
</div>



    <div class="mb-3">
    <input type="submit" class="btn btn-dark text-light px-4" >
  </div>
</form>
</div>
{% endblock %}

ecommerce/templates/cart.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class="container mt-5 p-3 border border-1 border-dark" style="margin-bottom:100px:">
    <h2 class="text-center">Shopping Cart</h2>
    <div class="row">
        <div class="col-7">
            <table class="table table-bordered text-dark fw-bold">
                <tr>
                    <th colspan="7">Cart Items</th>
                </tr>

                {% for i in cart %}
                <tr>
                <td class="p-3">
                    <img src="{{ i.product.image.url }}" height="150px" width="100px" class="img-thumbnail">
                </td>
                <td>Product:{{ i.product.name }}</td>
                <td>Quantity:{{i.quantity}}<br>
                    Unit price:{{ i.product.price }}</td>
                <td>Subtotal:{{i.subtotal}}</td>
                    <td>
                        {% if i.product.stock > 0 %}
                        <a href="{% url 'cart:addtocart' i.product.id %}"><i class="fa-solid fa-circle-plus text-danger " ></i></a>
                    <a href="{% url 'cart:cart_remove' i.product.id %}"><i class="fa-solid fa-circle-minus text-danger" ></i></a>
                    <a href="{% url 'cart:cart_fullremove' i.product.id %}"><i class="fa-solid fa-trash text-danger" ></i></a>
                        {% else %}
                        <a href="{% url 'cart:cart_remove' i.product.id %}"><i class="fa-solid fa-circle-minus text-danger" ></i></a>
                    <a href="{% url 'cart:cart_fullremove' i.product.id %}"><i class="fa-solid fa-trash text-danger" ></i></a>
                        {% endif %}
                    </td>
                </tr>



        {% endfor %}

            </table>
        </div>
        <div class="col-4">
            <table class="table table-bordered text-center">
                <tr>
                    <th colspan="4">CheckOut</th>
                    </tr>
                <tr><td><b>Total:{{total}}</b></td></tr>


            </table>
            <div class="d-flex justify-content-between">
    <a href="{% url 'cart:orderform' %}" class="btn btn-danger">Place Order</a>
    <a href="{% url 'shop:categories' %}" class="btn btn-danger">Continue Shopping</a>
</div>

        </div>
    </div>
</div>
{% endblock %}

ecommerce/templates/detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container mx-auto">


    <div class="card mb-3" style="max-width: 540px;">
  <div class="row g-0">

    <div class="col-md-4">
      <img src="{{pro.image.url}}" >
    </div>
    <div class="col-md-8">
      <div class="card-body">
        <h5 class="card-title">{{pro.name}}</h5>
        <p class="card-text">{{pro.desc}}</p>
        <p>{{pro.price}}</p>
        <p>{{pro.stock}}</p>
        {% if user.is_superuser %}   <!--if user is admin -->
           {% if pro.stock > 0 %}
            <p>Product in Stock</p>
            <a href="{% url 'shop:addstock' pro.id %}" class="btn btn-primary">Add Stock</a>
           {% else %}
              <p>Product OutOfStock</p>
            <a href="{% url 'shop:addstock' pro.id %}" class="btn btn-primary">Add Stock</a>
           {% endif %}
        {% else %}
           {% if pro.stock > 0 %}
            <p>Product in Stock</p>
            <a href="{% url 'cart:addtocart' pro.id  %}" class="btn btn-primary">Add to Cart</a>
           {% else %}
              <p>Product OutOfStock</p>
           {% endif %}
        {% endif %}

      </div>
    </div>
  </div>
</div>










</div>
{% endblock %}

ecommerce/templates/login.html
{% extends 'base.html' %}
{% load static %}
{% block content %}


<div class="container mt-3 text-dark">

<h1 class="text-center">Login here</h1>
<form method="POST" >
    {% csrf_token %}
     <div class="mb-3">
  <label  class="form-label">Username</label>
  <input type="text" class="form-control" name="u" placeholder="enter username">
</div>
<div class="mb-3">
  <label  class="form-label">Password</label>
  <input type="password" class="form-control" name="p" placeholder="enter password">
</div>
    <div class="mb-3">
    <input type="submit" class="btn btn-dark text-light px-4" >
  </div>
</form>
</div>
{% endblock %}

ecommerce/templates/orderform.html
{% extends 'base.html' %}
{% load static %}
{% block content %}


<div class="container mt-3 text-dark bg-secondary">

<h1 class="text-center">Billing Details</h1>
<form method="POST" >
    {% csrf_token %}
     <div class="mb-3">
  <label class="form-label">Address</label>
         <textarea name="a" class="form-control" placeholder="Write address here"></textarea>
     </div>
<div class="mb-3">
  <label  class="form-label">Phone</label>
  <input type="number" class="form-control" name="pn" placeholder="enter phone">
</div>
    <div class="mb-3">
  <label  class="form-label">Pin</label>
  <input type="number" class="form-control" name="n" placeholder="enter pin">
</div>
    <div class="mb-3">
    <input type="submit" class="btn btn-dark text-light px-4" >
  </div>
</form>


</div>
{% endblock %}

ecommerce/templates/orderview.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container mt-3 text-dark bg-secondary">
<h1 class="text-center">Your Orders</h1>
<h2 class="text-center">Customer name:{{user.username}}</h2>


{% for i in orders %}
<div class="card mb-3 mx-auto border border-1 border-danger" style="max-width: 540px;">
  <div class="row g-0">
    <div class="col-md-4">
      <img src="{{i.product.image.url}}" class="img-fluid rounded-start" height="200px" width="100%" alt="...">
    </div>
    <div class="col-md-8">
      <div class="card-body">
        <h4 class="card-title">Productname:<b>{{i.product.name}}</b></h4>
        <p class="card-text text-dark">Price:<b>{{i.product.price }}</b></p>
        <p class="card-text text-dark">Numerofitems:<b>{{i.no_of_items}}</b></p>
        <p class="card-text text-dark">Order_id:<b>{{i.order_id}}</b></p>
        <p class="card-text text-dark">Ordered on:<b>{{i.ordered_date}}</b></p>
        <p class="card-text"><b class="text-danger">Delivery_status:{{i.delivery_status}}</b></p>


      </div>
    </div>
  </div>
</div>

{% endfor %}}
</div>
{% endblock %}

ecommerce/templates/payment-status.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container mt-3 text-dark bg-secondary">
<h1 class="text-center">Payment Successful</h1>

</div>
{% endblock %}

ecommerce/templates/payment.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container mt-3 text-dark bg-secondary" >
    <center>
<form action="{% url 'cart:status' name %}" method="POST">
<script
   src="https://checkout.razorpay.com/v1/checkout.js"
    data-key="rzp_test_HSpVqk4ONJaQSA" // Enter the Test API Key ID generated from Dashboard → Settings → API Keys
    data-amount="{{payment.amount}}" // Amount is in currency subunits. Hence, 29935 refers to 29935 paise or ₹299.35.
    data-currency="INR"// You can accept international payments by changing the currency code. Contact our Support Team to enable International for your account
    data-order_id="{{payment.id}}"// Replace with the order_id generated by you in the backend.
    data-buttontext="Pay with Razorpay"
    data-name="My Shop"
    data-description="A Wild Sheep Chase is the third novel by Japanese author Haruki Murakami"
    data-image="https://example.com/your_logo.jpg"
    data-prefill.name="{{user}}"
    data-prefill.email="gaurav.kumar@example.com"
    data-theme.color="gray"
</script>
<input type="hidden" custom="Hidden Element" name="hidden"/>
</form>
    </center>
</div>
{% endblock %}

ecommerce/templates/products.html
{% extends 'base.html' %}
{% block content %}

<div class="container-fluid mt-5 ms-0">
    <img src="{{cat.image.url}}" height="500px" width="100%" >
</div>


<div class="container">
 <div class="row justify-content-center">
        <h1 class="section-title text-center mt-4" data-aos="fade-up">{{cat.name}}</h1>
        <div class="col-md-6 text-center" data-aos="fade-up" data-aos-delay="300">
          <p>{{cat.desc}}</p>

        </div>
 </div>



 <section class="categories overflow-hidden">
    <div class="container">
      <div class="open-up" data-aos="zoom-out">
        <div class="row">
          {% for i in pro %}
          <div class="col-md-4">
            <div class="cat-item image-zoom-effect">
              <div class="image-holder">
                <a href="index.html">
                  <img src="{{i.image.url}}" height="300px" width="100%" alt="categories" >
                </a>
              </div>
                <div class="category-content">
                <div class="product-button">
                  <a href="" class="btn btn-common text-uppercase">{{i.name}}</a>
                    <h5>{{i.price}}</h5>
                     <a href="{% url 'shop:detail' i.id %}">Details</a>

                </div>
              </div>

            </div>
          </div>
          {% endfor %}

        </div>
      </div>
    </div>
  </section>




{% endblock %}

ecommerce/templates/register.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container mt-3 text-dark">
<h1 class="text-center">Register here</h1>
<form method="POST" >
    {% csrf_token %}
     <div class="mb-3">
  <label  class="form-label">Username</label>
  <input type="text" class="form-control" name="u" placeholder="enter username">
</div>
<div class="mb-3">
  <label  class="form-label">Password</label>
  <input type="password" class="form-control" name="p" placeholder="enter password">
</div>
<div class="mb-3">
  <label  class="form-label">Confirm Password</label>
  <input type="password" class="form-control" name="cp" placeholder="enter confirm password">
</div>
    <div class="mb-3">
  <label  class="form-label">Email</label>
  <input type="text" class="form-control" name="e" placeholder="enter email">
</div>
     <div class="mb-3">
  <label  class="form-label">Firstname</label>
  <input type="text" class="form-control" name="f" placeholder="enter first name">
</div>
    <div class="mb-3">
  <label  class="form-label">Lastname</label>
  <input type="text" class="form-control" name="l" placeholder="enter last name">
</div>
    <div class="mb-3">
    <input type="submit" class="btn btn-dark text-light px-4" >
  </div>


</form>
</div>
{% endblock %}

ecommerce/templates/search.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<center>
    <div class="container mt-3 bg-dark text-light">
{% if pro == None %}

<h2 class="text-center text-light">Search Products</h2>
<form method="POST" >
    {% csrf_token %}
     <div class="mb-3">
         <input type="text" class="form-control" name="q">
         <input type="submit" class="btn btn-secondary " >
     </div>
</form>
</div>
    {% else %}

    <section class="categories overflow-hidden">
    <div class="container">
      <div class="open-up" data-aos="zoom-out">
        <div class="row">
          {% for i in pro %}
          <div class="col-md-4">
            <div class="cat-item image-zoom-effect">
              <div class="image-holder">
                <a href="index.html">
                  <img src="{{i.image.url}}" height="300px" width="100%" alt="categories" >
                </a>
              </div>
                <div class="category-content">
                <div class="product-button">
                  <a href="" class="btn btn-common text-uppercase">{{i.name}}</a>
                    <h5>{{i.price}}</h5>
                     <a href="{% url 'shop:detail' i.id %}">Details</a>

                </div>
              </div>

            </div>
          </div>
      {% empty %}
            <h2 class="text-center">No Results</h2>
            {% endfor %}


        </div>
      </div>
    </div>
  </section>

{% endif %}
</center>
{% endblock %}